### ISSUE TITLE
"android-support-v7-appcompat" will support?

### ISSUE THREAD

**Issue by rserega** [dot42/dot42#25]

**Comment by OlafPettersson** [comment]
At the moment, v4 and v13 are accessible when you check 'Android Support Library' in Visual Studio. Why would you need v7?

**Comment by rserega** [comment]
For support AppCompatActivity in previous versions (2.1...2.2...).

**Comment by OlafPettersson** [comment]
Have you tried to import the v7 support library like any other .jar? There are some hints on how to reference .jars in your project in BUGS_AND_LIMITATIONS.md; here are the relevant (a little bit technical) parts:

Importing jar references should work, but I could not get Intellisense/Resharper to work out of the box. When importing a jar reference (or when the underlying jar has changed) Dot42 creates a `.cs` -File with CLR compatible types, that can be accessed as normal during development. All references to them will magically be replaced to the actual implementation when compiling to `.dex`. This generated file is put in the `obj` intermediate directory, and not part of the project. Therefore Intellisense does not work.
  What worked for me (with Resharper) is to have a dedicated import project that does nothing else but import jar-references. I don't even worry about unused references, since dot42 is smart enough to not compile them into the final `.apk`. Then I don't reference the import project itself, but the assembly it generates. This make IntelliSense to work as expected.

**Comment by rserega** [comment]
I imported *.jar when trying to add advertising AdMob. The result is described in another topic. Got a *.apk not working

**Comment by OlafPettersson** [comment]
I'm closing this issue for know. If the problem persists, feeld free to reopen the issue.
