### ISSUE TITLE
debugging problem

### ISSUE THREAD

**Issue by estebanjb** [dot42/dot42#29]
Hello. 

I'm compiling and running C# programs with the dot42 plugin for Visual Studio 2010 and it's working very good,  but I'm having a problem with the debugger, It isn't showing the variable values and is showing me the error _"Unnable to evaluate the expression"_ . Does anybody handled this issue before?

The next image is the attempt to perform a quickwatch over a generic List.

![image](https://cloud.githubusercontent.com/assets/12928275/13095691/99745296-d4f2-11e5-9b2b-7b66dcc4348f.png)

Why isnt it showing the items of the list like normal C# code?

Thanks, Esteban.

**Comment by OlafPettersson** [comment]
When debugging in "Release" mode, variables will not be available. I am assuming you are debugging in "Debug" mode.

In general, Dot42 is only able to show local variables and method parameters, including 'this'. It does not evaluate properties as these entail a method call, which is impossible to perform without side effects on Android, even for read-only properties.
Dot42 does not automatically evaluate member variables. To show these, type in 'this' and expand the view. Personally I think the best approach is to use the "Locals"-Debug Window, which will show all available local variables.
Also note that due to a bug in the Dalvik VM in rare cases Dot42 is unable to evaluate a single/specific variable in a method. This limitation does not apply for ART / Android 5.x.

Does any of this apply to you?

**Comment by OlafPettersson** [comment]
I'm closing this issue for now, as the limitation is due to a technical android issue. Feel free to re-open it if neccessary.
